// Generated by React Component Generator
// Command: make-component Button -p text:string,onClick:()=>void
// Generated at: 2025-09-19T01:22:08.931Z

import React from 'react';
import './Button.css';

interface ButtonProps {
  text: string;
  onClick: ()=>void;
}

const Button = (props: ButtonProps) => {
  return (
    <div className="container"></div>
  );
};

export default Button;